# Generated by Django 3.2.7 on 2022-02-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coordinateWiseData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gridId', models.TextField()),
                ('gridx', models.TextField()),
                ('gridy', models.TextField()),
                ('today', models.TextField()),
                ('tonight', models.TextField()),
                ('monday', models.TextField()),
                ('monday_night', models.TextField()),
                ('tuesday', models.TextField()),
                ('tuesday_night', models.TextField()),
                ('wednesday', models.TextField()),
                ('wednesday_night', models.TextField()),
                ('thursday', models.TextField()),
                ('thursday_night', models.TextField()),
                ('friday', models.TextField()),
                ('friday_night', models.TextField()),
                ('saturday', models.TextField()),
                ('saturday_night', models.TextField()),
                ('sunday', models.TextField()),
                ('sunday_night', models.TextField()),
                ('lastupdated', models.TextField()),
            ],
        ),
    ]
