# Generated by Django 3.2.7 on 2022-02-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherDetails', '0002_auto_20220214_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatewisedata',
            name='latitude',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coordinatewisedata',
            name='longitude',
            field=models.TextField(default=''),
        ),
    ]
